### PR TITLE
Adding KeyError to accepted exceptions in conftest

### PR DESCRIPTION
**Pull request by bsipocz**
``gwcs`` imports ``pyasdf.tests.helpers``, that imports from its ``..conftest``.

However, ``conftest.py`` exists in both packages, and as they both use the astropy package-template, both has ``PYTEST_HEADER_MODULES`` variable. None of the packages has the dependency of ``h5py``, and trying to delete it from the ``PYTEST_HEADER_MODULES`` dict twice raises an Error. 

This PR is the workaround to solve this.

### CODE REVIEW

**Comment by bsipocz** [comment]
Related package template PR: https://github.com/astropy/package-template/pull/143

**Comment by bsipocz** [comment]
Related package template PR: https://github.com/astropy/package-template/pull/143

**Comment by bsipocz** [comment]
@nden - This fails with the known conda path issue. Do you want to use ``ci-helpers`` here, too or should I just update the path?

**Comment by nden** [comment]
:+1:  for using `ci-helpers` from me. @embray?

**Comment by embray** [comment]
Makes sense--this is just a dumb oversight probably carried over from astropy.

**Comment by embray** [comment]
pyasdf should also switch over to the new system.  That should be done via package-template though, right?

**Comment by nden** [comment]
Just so I understand, is this waiting for astropy/package-template#143 to be merged?

**Comment by embray** [comment]
I think so.

**Comment by bsipocz** [comment]
@nden, @embray - https://github.com/astropy/package-template/pull/143 is the same as this one, as I understood @embray's comments above it's more like a waiting for https://github.com/astropy/package-template/pull/140 for the ``ci-helpers`` stuff in the template. (Alternatively https://github.com/astropy/package-template/pull/143 can be pulled, too and close this without merging).

Please let me know if it was misunderstood, and you are actually waiting me to put the ``ci-helpers`` in, with this PR.

Both of those PR for the package-template are ready to be merged when a maintainer is around, I think.

**Comment by nden** [comment]
@bsipocz I see now. In this case I think it's best to include in this PR everything necessary to run pyasdf tests now. We can update the templates when they are ready.

**Comment by embray** [comment]
Honestly, it would be fine to just merge this PR--it doesn't impact the actual test results in relevant way.  If no one disagrees I'll merge.

**Comment by bsipocz** [comment]
@embray - Either way. I'm travelling tomorrow, so I can put in the ci stuff then given that this is still unmerged.

**Comment by bsipocz** [comment]
OK, done now. Just a note, that you may want to revise the travis matrix, as atm the tests only run on 2.7  as the rest of the versions have only the egg-info checks.

**Comment by bsipocz** [comment]
Another change I made that appveyor now installs gwcs as well as a dependency (it seemed that it wasn't installed before).

**Comment by embray** [comment]
Strange about the Windows build, but it seems like it might be a path separator issue in pyasdf's setup.  I'll have a look at it.

**Comment by nden** [comment]
Or is it not pulling in the `asdf-standard` submodule when it builds pyasdf?

**Comment by embray** [comment]
@nden You're right, that's all it is.  The build recipe needs to make sure to `git submodule --init asdf-standard`.

**Comment by nden** [comment]
@embray I think this should be merged as is. appveyor can be fixed after that.

**Comment by embray** [comment]
@nden Sure, I'll do that. I think maybe @bsipocz is on travel now.

**Pull request merged**
