### PR TITLE
WIP: Generalized WCS -- try #3

### PR DESCRIPTION
**Pull request by mdboom**
This is a work-in-progress to get the generalized WCS stuff serializing to/from ASDF.

All of this is written against embray/astropy@9307fbafe741 (the compound modeling branch).

There's a few things in modeling that I either don't understand or need improvement:

- [ ] Models don't have equality defined, so it doesn't seem to be possible to serialize a model from disk, reload it and compare it against the original.  Is that a hard thing to add?

- [ ] I've had to use some private APIs related to compound models (see `compound.py` below).  Any thoughts about how to provide a public API to what I need?

- [ ] modeling only has an AffineTransformation2D.  What would be involved in making it n-dimensional?  In general, I don't think we should have separate classes for different dimensionality, with the exception of the very-specialized projections (TAN, XPH etc.) where n-dimensionality doesn't make sense.

### CODE REVIEW

**Comment by mdboom** [comment]
@embray: This has been updated to work with current astropy master and is passing the tests (hooray!).  The one outstanding issue is using the `._tree` member of compound models in order to introspect the tree and serialize it to YAML.  (See `compound.py` for what exactly it does).  Any thoughts about how to make a public API for that?  Maybe just add a property `tree` that returns `_tree`?

**Comment by embray** [comment]
That might be a start.  How do you feel about the expression tree interface itself?  I think it's fairly easy to use, but part of me wants something "better" where exactly what that is remains undefined.

I'm also increasingly unhappy with how the tree is represented internally.  For a binary tree like this it would be easy to represent the nodes as a flat list rather than a nested data structure, while still providing the same user-level interface.  There are several algorithms that I feel like would be simpler if the tree were represented this way, rather than having to traverse the nodes as is currently necessary.  But that's more of an internal detail...

**Comment by mdboom** [comment]
@embray: On the naming issue: How about this:

- `&`: concatenate
- `|`: compose

**Comment by nden** [comment]
@mdboom What is the plan for this PR? I am using it locally but it would be easier if it's merged now, even if things are changed later.

**Comment by mdboom** [comment]
I've been working on it a bit but mainly been sidetracked.  I'm fine with merging it and continuing to improve it incrementally, though.

**Comment by mdboom** [comment]
I'll give Travis-CI a chance to test this, and then merge.

**Comment by nden** [comment]
Great! Thanks!

And a question - given an asdf file, I see how I can read/open it, but how can I generate a model object from it?

**Comment by mdboom** [comment]
The work to join `jwst_lib.models` and ASDF is still ongoing.  It's been the bane of my existence for some time...

**Comment by nden** [comment]
Sorry, overloaded term again. How do I generate an astropy.modeling model? For example, given a rotated2d.asdf file (and since there's a schema for it), what is the command to get a `modeling.Rotation2D` object. I feel like I'm missing something simple.

**Comment by mdboom** [comment]
:laughing: overloading models again...

You would do `asdffile.tree['my_model']` to get it (where `my_model` is just wherever you happened to store the transform in the tree.  The conversion from modeling objects to YAML and back happens automatically.

**Comment by nden** [comment]
Here's my asdf file:

```
#ASDF 0.1.0
%YAML 1.1
%TAG ! tag:stsci.edu:asdf/0.1.0/
--- !core/asdf
smallrotation: !transform/rotate2d
  angle: 2.4
...
```
I get a dictionary
```
 rot=pyasdf.AsdfFile.read('rot.asdf')
 rot.tree['smallrotation']
Out[33]: {u'angle': 2.4}
```
Is my asdf file wrong?

**Comment by mdboom** [comment]
Ah -- it's a bug with this PR.  The transform classes weren't getting imported (and the unit tests did this, so they weren't catching this).  I'll have an update here momentarily.

**Comment by mdboom** [comment]
I think this is working now, but @nden, would you mind double-checking before I merge?

**Comment by nden** [comment]
Yep, it works.

**Comment by nden** [comment]
I think the name of this method `asdffile.tree` is confusing. I didn't think it was a bug since it returned a dictionary and I thought it represented the tree of models.

**Comment by mdboom** [comment]
It's the tree of objects stored in the ASDF file.  http://asdf-standard.readthedocs.org/en/latest/tree.html  

You can store transforms anywhere in it -- it's just JSON/YAML data structures.  I agree it's not the greatest name -- it's what I've been using to refer to the main heirarchical content of the ASDF file.  Any suggestions?

**Comment by nden** [comment]
I guess I expected `.tree` to return the YAML data structure and something else to create the object, something like "instantiate" which is a terrible name. May be it's just me,  not very good at names.

**Pull request merged**
