### PR TITLE
Rename references to the repository 

### PR DESCRIPTION
**Pull request by olebole**
This is a preparation of the repository rename.

### CODE REVIEW

**Comment by nden** [comment]
The same problem as in #192 in travis. Merging this.

**Comment by nden** [comment]
@olebole v1.1 now on pypi. Thanks for your work.

**Comment by embray** [comment]
Thanks @nden and @olebole both for taking care of this!

**Comment by olebole** [comment]
asdf is now uploaded to Debian. Once it is accepted, it will appear [here](https://tracker.debian.org/pkg/python-asdf).

**Pull request merged**
