### PR TITLE
Should be '--init' not 'init'

### PR DESCRIPTION
**Pull request by embray**
Just fixes a typo that should get the appveyor builds going again on top of #180

### CODE REVIEW

**Comment by bsipocz** [comment]
Looking at the appveyor log of #180 it looks like the problem may be with the path (and init worked as is). Basically I don't have any windows experience, but mixing slashes and backslashes in the same path looks a bit weird.

```
WindowsError: [Error 3] The system cannot find the path specified: 'asdf-standard\\reference_files/*.*'
Command exited with code 1
```

**Comment by embray** [comment]
Oops, silly me, there's also a missing `update` subcommand.

**Comment by nden** [comment]
@embray This now only fails for Python 3.4 because `astropy` can't be build. Any ideas why the astropy build fails?

**Comment by embray** [comment]
It seems to be a configuration issue on their end, but I'm not sure.  It might work if I just re-run the build.

**Comment by embray** [comment]
It occurs to me that the pyasdf builds on appveyor are associated with @mdboom's appveyor account.  Really we should have an account for spacetelescope.  I'll get that set up...

**Comment by embray** [comment]
Well, on second thought, to create an appveyor account for spacetelescope I need to give an e-mail address and such.  So maybe someone else should do that.  I will, however, transfer pyasdf to the Astropy appveyor account for now.

**Comment by embray** [comment]
Well I'm getting lost in various account settings for AppVeyor and GitHub and it's making my head spin.  I'll come back to this when I'm not already feeling sick...

**Comment by bsipocz** [comment]
Also as v1.1 is out you can change the test and conda install ``'stable'`` rather than building the dev version for several python versions.

**Comment by nden** [comment]
@bsipocz is right. We need only one `astropy dev` build now. The reason for having `dev` in all builds was a change in `modeling` that is now released in 1.1 .

I've just looked at Appveyor for the first time but as I understand it, transferring of project ownership cannot be done easily and may only be possible if the current owner asks the Appveyor admins to do it. It may be better to configure the current appveyor account to allow more people with "Administrator" roles for pyasdf.

**Comment by nden** [comment]
spacetelescope has now AppVeyor permissions and I've restarted the build.

**Comment by embray** [comment]
Took a bit of fooling around, but I was able to reproduce locally what appveyor is doing when running the builds, and reproduced the build problem on Python 3.4.  I suspect the problem is in anaconda, but it could just be some environment variables that need to be twiddled.  Will find out more later.

**Comment by embray** [comment]
I think astropy/ci-helpers#34 will take care of the Python 3.4 build problems (apologies for pointing the finger to anaconda--the reason I wasn't able to reproduce this before is because my stock Python environment on Windows is all 32-bit.

**Comment by embray** [comment]
\o/

**Pull request merged**
