### PR TITLE
Rename package to asdf

### PR DESCRIPTION
**Pull request by olebole**
This pull request solves (partially) #186 in the way that the library is renamed from pyasdf to asdf.
I will apply this patch to the Debian version of asdf so that the version 1.0.1-1 there will have this name.

**Please indicate whether this is OK for you or not.** It will be hard to change the name once the package is there, but I want to advertize the format a bit, and enable the users to play with it.

### CODE REVIEW

**Comment by nden** [comment]
:+1:

**Comment by embray** [comment]
Wow, thanks @olebole !  This should mostly resolve the issue, other than swapping RTD accounts.

There were a few errors in the docs build--I don't know if those errors were occurring before or not, but I do see some remaining references to "pyasdf" that might have been missed.

We should also rename this repository on GitHub just to be clear.

**Comment by olebole** [comment]
@embray I found the missing piece for the rename; it was the directory `docs/pyasdf`.
For the error in the docs, I have no idea at all. They appear on the lines like
```
.. asdf:: example.asdf
```
which were not renamed by the first commits of this PR. They lead to 
```
/home/travis/build/spacetelescope/pyasdf/docs/index.rst:52: WARNING: Could not parse literal_block as "yaml". highlighting skipped.
```

I first thought of some name conflict and renamed the directive to `asdfdata`; this owever does not help. I could imagine that this happens as well in the original branch (maybe depending on the sphinx release).
Could I request some help here? I am not familar with sphinx extensions.

**Comment by embray** [comment]
It's possible the sphinx extension broke somewhere along the line or isn't being installed properly.  I have a feeling those errors are not due to your changes but I'm not sure (the others were, but that was a simple fix).

**Comment by embray** [comment]
This looks to be related: https://github.com/sphinx-doc/sphinx/issues/2264

@olebole for the "revert" what I really meant was a rebase / squash--no need for an actual revert commit.

**Comment by embray** [comment]
I think after this we can move on--it seems to issue with yaml highlighting is not related to your changes.  Thanks again!

**Comment by olebole** [comment]
OK, I did a squash (hopefully correctly).

**Comment by olebole** [comment]
@embray Could I ask to merge this PR and create a new version then? Otherwise, I would need to create a Debian package that differs quite significantly from the official upstream package.

**Comment by nden** [comment]
Unless there's an objection I will merge this PR later today.

**Comment by olebole** [comment]
Thank you very much! Would you mind to also create a new release and upload to pypi?

**Comment by nden** [comment]
I tagged a new version as 1.0.2. Will upload it as soon as I get permissions on pypi.

**Comment by olebole** [comment]
Now there is a 1.0.2 version registered on pypi, but no files associated with it.

**Comment by embray** [comment]
I think we should be calling this "1.1.0" at the very least considering it completely changed the name of the package :)

**Comment by embray** [comment]
We should also change the name of this GitHub repository to further reduce confusion.

**Comment by embray** [comment]
Similarly I think the dropping of Python 2.6 should be a 1.x release, not a patch release.  Though it's less important for asdf since it doesn't have a wide user base yet.  

But yeah, patch releases should only be to fix bugs--it shouldn't include major interface changes.

**Comment by nden** [comment]
pypi refused to upload the files and we are still trying to sort out the permissions. 
I'll send a note when the files are there, will probably need to tag a new version, so 1.1 may come out as @embray recommends. Changing the name of the repository requires even more coordination with other groups. It will happen eventually, just not right now. 
@embray Do you have permissions for the RTD account and can you assist in switching the accounts?

**Pull request merged**
