### PR TITLE
Adding numpy dependency to setup.py 

### PR DESCRIPTION
**Pull request by bsipocz**
as the hard astropy dependency was lifted a while ago

### CODE REVIEW

**Comment by embray** [comment]
:+1: Wondering if we should specify a minimum version.  I'm not too concerned about it right now, but if we did I'd say 1.8...

**Comment by bsipocz** [comment]
@embray - 1.8 is added.

**Comment by embray** [comment]
Thanks!

**Comment by bsipocz** [comment]
@embray - I wonder whether it's possible to also update this metadata of the released version on pypi?

**Comment by embray** [comment]
That can be done through PyPI on the web interface.  However, I don't believe PyPI displays dependency metadata, currently.

**Comment by embray** [comment]
Oops, should have merged this for 1.0.1.  Oh well, next time.

**Pull request merged**
